import rhinoscriptsyntax as rs
rs.AddBox([[437.3030707610147, -477.0, -352.19667800818337], [437.3030707610147, -477.0, 352.19667800818337], [437.3030707610147, 477.0, 352.19667800818337], [437.3030707610147, 477.0, -352.19667800818337], [516.6969292389854, -477.0, -352.19667800818337], [516.6969292389854, -477.0, 352.19667800818337], [516.6969292389854, 477.0, 352.19667800818337], [516.6969292389854, 477.0, -352.19667800818337]])
rs.AddBox([[-516.6969292389854, -477.0, -352.19667800818337], [-516.6969292389854, -477.0, 352.19667800818337], [-516.6969292389854, 477.0, 352.19667800818337], [-516.6969292389854, 477.0, -352.19667800818337], [-437.3030707610147, -477.0, -352.19667800818337], [-437.3030707610147, -477.0, 352.19667800818337], [-437.3030707610147, 477.0, 352.19667800818337], [-437.3030707610147, 477.0, -352.19667800818337]])
rs.AddBox([[-437.3030707610147, -477.0, -352.19667800818337], [-437.3030707610147, -477.0, -217.19667800818337], [-437.3030707610147, 477.0, -217.19667800818337], [-437.3030707610147, 477.0, -352.19667800818337], [437.3030707610147, -477.0, -352.19667800818337], [437.3030707610147, -477.0, -217.19667800818337], [437.3030707610147, 477.0, -217.19667800818337], [437.3030707610147, 477.0, -352.19667800818337]])
rs.AddBox([[-437.3030707610147, -477.0, -217.19667800818337], [-437.3030707610147, -477.0, -61.19667800818337], [-437.3030707610147, 477.0, -61.19667800818337], [-437.3030707610147, 477.0, -217.19667800818337], [437.3030707610147, -477.0, -217.19667800818337], [437.3030707610147, -477.0, -61.19667800818337], [437.3030707610147, 477.0, -61.19667800818337], [437.3030707610147, 477.0, -217.19667800818337]])
rs.AddBox([[-437.3030707610147, 397.60614152202936, -61.19667800818337], [-437.3030707610147, 397.60614152202936, 591.1966780081834], [-437.3030707610147, 477.0, 591.1966780081834], [-437.3030707610147, 477.0, -61.19667800818337], [437.3030707610147, 397.60614152202936, -61.19667800818337], [437.3030707610147, 397.60614152202936, 591.1966780081834], [437.3030707610147, 477.0, 591.1966780081834], [437.3030707610147, 477.0, -61.19667800818337]])
rs.AddCylinder([477.0, 404.0, -528.435152808665], 176.23847480048164, 36.5, True)
rs.AddCylinder([-477.0, 404.0, -528.435152808665], 176.23847480048164, 36.5, True)
rs.AddCylinder([477.0, -404.0, -528.435152808665], 176.23847480048164, 36.5, True)
rs.AddCylinder([-477.0, -404.0, -528.435152808665], 176.23847480048164, 36.5, True)
