import rhinoscriptsyntax as rs
rs.AddBox([[468.6127819548872, -480.5, -403.9334722451211], [468.6127819548872, -480.5, 403.9334722451211], [468.6127819548872, 480.5, 403.9334722451211], [468.6127819548872, 480.5, -403.9334722451211], [492.3872180451128, -480.5, -403.9334722451211], [492.3872180451128, -480.5, 403.9334722451211], [492.3872180451128, 480.5, 403.9334722451211], [492.3872180451128, 480.5, -403.9334722451211]])
rs.AddBox([[-492.3872180451128, -480.5, -403.9334722451211], [-492.3872180451128, -480.5, 403.9334722451211], [-492.3872180451128, 480.5, 403.9334722451211], [-492.3872180451128, 480.5, -403.9334722451211], [-468.6127819548872, -480.5, -403.9334722451211], [-468.6127819548872, -480.5, 403.9334722451211], [-468.6127819548872, 480.5, 403.9334722451211], [-468.6127819548872, 480.5, -403.9334722451211]])
rs.AddBox([[-468.6127819548872, -480.5, -403.9334722451211], [-468.6127819548872, -480.5, -236.74196528379247], [-468.6127819548872, 480.5, -236.74196528379247], [-468.6127819548872, 480.5, -403.9334722451211], [468.6127819548872, -480.5, -403.9334722451211], [468.6127819548872, -480.5, -236.74196528379247], [468.6127819548872, 480.5, -236.74196528379247], [468.6127819548872, 480.5, -403.9334722451211]])
rs.AddBox([[-468.6127819548872, -480.5, -236.74196528379247], [-468.6127819548872, -480.5, -74.36893796706107], [-468.6127819548872, 480.5, -74.36893796706107], [-468.6127819548872, 480.5, -236.74196528379247], [468.6127819548872, -480.5, -236.74196528379247], [468.6127819548872, -480.5, -74.36893796706107], [468.6127819548872, 480.5, -74.36893796706107], [468.6127819548872, 480.5, -236.74196528379247]])
rs.AddBox([[-468.6127819548872, 456.72556390977445, -74.36893796706107], [-468.6127819548872, 456.72556390977445, 520.933472245121], [-468.6127819548872, 480.5, 520.933472245121], [-468.6127819548872, 480.5, -74.36893796706107], [468.6127819548872, 456.72556390977445, -74.36893796706107], [468.6127819548872, 456.72556390977445, 520.933472245121], [468.6127819548872, 480.5, 520.933472245121], [468.6127819548872, 480.5, -74.36893796706107]])
rs.AddCylinder([480.5, 455.5, -643.2345378507719], 239.30106560565082, 12.5, True)
rs.AddCylinder([-480.5, 455.5, -643.2345378507719], 239.30106560565082, 12.5, True)
rs.AddCylinder([480.5, -455.5, -643.2345378507719], 239.30106560565082, 12.5, True)
rs.AddCylinder([-480.5, -455.5, -643.2345378507719], 239.30106560565082, 12.5, True)
